---
plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  tag:Project: p01-webha
  tag:Environment: dev
  instance-state-name: running

hostnames:
  - private-ip-address

compose:
  ansible_host: private_ip_address

groups:
  webservers: "'p01-webha' in tags.Project"
